### PR TITLE
Add upload progress bar

### PR DESCRIPTION
**Pull request by maxclaus**
It is hard to understand what is going on without a progress bar.
Since my internet is pretty bad. While I was publishing a new version
for my app I thought something wrong had happened because was taking
too much time to finish the process. At least with a progress bar I know
the upload still happening.

Example:
upload-progress

### CODE REVIEW

**Comment by jenslind** [comment]
@maxcnunes Nice, thanks!
I'm just thinking we might wanna do the rendering in `cli.js` instead.

**Comment by maxclaus** [comment]
Yeah. Makes sense. I'm gonna change it later today.

**Comment by maxclaus** [comment]
I have changed the code to show the progress bar only if the verbose option is enabled. I didn't want to move the progress bar to the `cli.js` file because it would require exposing the `publishRelease` object and it would change too munch your original code. I guess is simpler this way.

**Comment by jenslind** [comment]
:+1:

**Pull request closed without merging**
